### ISSUE TITLE
Show "Old Value" for deleted related entity

### ISSUE THREAD

**Issue by nperno** [biasmey/EF.Audit#4]
Hello, Thanks for making this, it works great!. Question - is there a way to make this show a property of a deleted sub or related entity in the "OldValue" column? It creates a line in the DB for the deletion, it just doesn't show what record was actually deleted (at least in a human readable way). Any thoughts?

**Comment by biasmey** [comment]
Is fine , this information was serializing  in db . You can  using GetHistory or  GetSnapshot methods   for get this information . These methods are extend to DbContext

example 
var entity =  context.Set<entityType>().Find(key)
 var snapshot = context.GetSnapshot(DateTime.Now, entity);
 var history = context.GetHistory<Person,MyContext>(DateTime.Now, context.GetEntityKey(entity));
